### ISSUE TITLE
`RealtimeDBPagination` Doesn't update when new child nodes are added.

### ISSUE THREAD

**Issue by p4-k4** [OutdatedGuy/firebase_pagination#10]
The widget doesn't rebuild or maybe doesn't even update the data when adding a child node in Realtime Database (as per my last issue) with `isLive` set as true.

**Comment by OutdatedGuy** [comment]
Sorry for the late response. I'll look into the matter ASAP.

**Comment by OutdatedGuy** [comment]
@flutterfocus, are you try this on mobile device?

If yes then, can you confirm the same happens on the web platform.

**Comment by OutdatedGuy** [comment]
Closing this issue as no response was received.

If the problem still persists, leave comment and I'll reopen this issue.

**Comment by p4-k4** [comment]
> Closing this issue as no response was received.
> 
> 
> 
> If the problem still persists, leave comment and I'll reopen this issue.

Does the widget rebuild for you on the respective platforms for every time a child node is added in RTDB?

Or can you clarify that it **should** rebuild when a child node is added? TBH I was merely just testing your package that's all and stumbled on this issue.

I would assume it should but after a quick glance of the code base, I didn't see anything obvious for this specific case.

I was just reporting this as a potential issue if it was worth your time checking it out as I actually use my own package for pagination.

**Comment by OutdatedGuy** [comment]
I'm seeing some unusual behavior of package on different platforms for some reason. On web, it runs as expected, but on mobile it sometimes fails.

Might be something to do it firebase packages itself, idk 🤷🏻

**Comment by p4-k4** [comment]
> I'm seeing some unusual behavior of package on different platforms for some reason. On web, it runs as expected, but on mobile it sometimes fails.
> 
> 
> 
> Might be something to do it firebase packages itself, idk 🤷🏻

Didn't look like the listener callback has implementations for those events to begin with, at least from from I can see. Up to you, whether it's something you want to look into 👍

**Comment by OutdatedGuy** [comment]
@flutterfocus, Ahhh, I finally understood the problem. Query for _Firestore_ and _RealtimeDB_ have some major differences.

1. _RealtimeDB_ query will always return data in ascending order unlike in _Firestore_ where you can set it.
2. _RealtimeDB_ does not have `startAt` or `startAfter` (node) like _Firestore_ which have `startAfterDocument` and `startAtDocument`

Due to these 2 major problems, it failed as I made their functioning identical.

**Comment by OutdatedGuy** [comment]
Yo @flutterfocus, can you please verify if the issue is solved.

### Steps to run

1. Clone the project
2. Copy the sample code in the `example/lib/main.dart` file
3. Provide your demo firebase project configuration when initializing firebase
4. Set firebase `realtime db` rules to allow all operations.
5. Run code and test with different configs (i.e. setting `isLive` on and off, etc.)

<details>
<summary>Sample Code</summary>

```dart
// Flutter Packages
import 'package:flutter/material.dart';

// Firebase Packages
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_database/firebase_database.dart';

// Third Party Packages
import 'package:firebase_pagination/firebase_pagination.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(
    options: const FirebaseOptions(
      // ...
    ),
  );

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Firebase Pagination Example',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Firebase Pagination Example'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final _textController = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: RealtimeDBPagination(
        query:
            FirebaseDatabase.instance.ref('messages').orderByChild('createdAt'),
        orderBy: 'createdAt',
        isLive: true,
        limit: 6,
        reverse: true,
        padding: const EdgeInsets.all(8.0),
        separatorBuilder: (context, index) => const Divider(),
        itemBuilder: (context, snapshot, index) {
          String? msg = (snapshot.value as Map<String, dynamic>?)?['text'];
          return ListTile(
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(8.0),
            ),
            tileColor: msg == null ? Colors.red : Colors.green,
            title: Text(
              msg ?? 'No Message',
            ),
          );
        },
      ),
      bottomNavigationBar: Container(
        color: Colors.white,
        padding: const EdgeInsets.all(8.0),
        child: Row(
          children: [
            Expanded(
              child: TextField(
                controller: _textController,
                decoration: const InputDecoration(
                  hintText: 'Enter a message',
                ),
              ),
            ),
            const SizedBox(width: 8.0),
            IconButton(
              icon: const Icon(Icons.send),
              onPressed: () async {
                await FirebaseDatabase.instance
                    .ref('messages')
                    .push()
                    .set(<String, dynamic>{
                  'text': _textController.text,
                  'createdAt': -DateTime.now().millisecondsSinceEpoch,
                });
                _textController.clear();
              },
            ),
          ],
        ),
      ),
    );
  }
}
```
</details>
