### ISSUE TITLE
New Data dosent ahown directly

### ISSUE THREAD

**Issue by saedfarashat** [OutdatedGuy/firebase_pagination#11]
When i add a new data it dosent show the new data directly ... I must close the screen and open it again to see the new data

**Comment by OutdatedGuy** [comment]
Yo @saedfarashat, thanks for filling this issue.

Can you attach the code snippet(text format) and error screenshot or video meanwhile.

I'll look into it.

**Comment by OutdatedGuy** [comment]
@saedfarashat, are you facing the issue on mobile platform?

If yes then, can you confirm the same happens on the web platform.

**Comment by OutdatedGuy** [comment]
Closing this issue as no response was received.

If the problem still persists, leave comment and I'll reopen this issue.

**Comment by OutdatedGuy** [comment]
Yo @saedfarashat, I got what caused the problem. If the added data doesn't have field that fires again, then data is not added.

Like, if you used `FieldValue.serverTimestamp()` for a field `createdAt` then it will fire twice and added once.
But if you used `DateTime.now().millisecondsSinceEpoch` for the same, it will not be added.

This is definitely a bug, thanks for the report.

**Comment by saedfarashat** [comment]
Hello
In this video you'll see where's the problem
Also there's a screenshot for the code

Video Link
https://drive.google.com/file/d/12OAD-_IdtKn9tdR94zqMbhjKz-Yx3GJY/view?usp=drivesdk

Image

**Comment by OutdatedGuy** [comment]
@saedfarashat, can you show the data structure for which you have written the query. The data structure in the Firestore.
And also the code that adds data in Firestore (code of flutter).

**Comment by OutdatedGuy** [comment]
@saedfarashat, please check the latest version on pub.dev
