### ISSUE TITLE
There is no index option in separatorBuilder for FirestorePagination

### ISSUE THREAD

**Issue by toufiksalhi** [OutdatedGuy/firebase_pagination#13]
Hi,first of all thanks for this amazing library, I don't know why it's not famouse. My issue  is I want to add some ads in my FirestorePagination
,I used separatorBuilder and it show an ad after every single list item ,but that's not what I want ,I want to show an ad after the user scroll 10 items for example,so how I can set the index of  separator ?

**Comment by OutdatedGuy** [comment]
Yo @toufiksalhi, I'm glad you liked the package.

Can you provide the code snippet of the `FirestorePagination` in your project. Cuz there is a index provider in separator builder.
It would be easy for me to help you with a code snippet.

**Comment by OutdatedGuy** [comment]
Closing this issue as no response was received.

If the problem still persists, leave comment and I'll reopen this issue.
