### ISSUE TITLE
Will this project be actively maintained? 

### ISSUE THREAD

**Issue by Omi231** [OutdatedGuy/firebase_pagination#2]
My apps have a lot of different lists for which i am using an existing package but the dev has not maintained it in last 2 years. I am not very good at programing so now I have to use some other package and move to a new package.

**Comment by OutdatedGuy** [comment]
Yo @Omi231, I'm still a college student, so I can maintain this package actively for a year or so. After that the package will be maintained but not actively as it is now.

Closing this for now

**Comment by Omi231** [comment]
Thanks man. Good luck for your college. 

I am encountering a problem can you help me in this? I want to use `PaginateFirestore` inside a `CustomScrollView` which has 2-3 slivers. 

`CustomScrollView(
    slivers:[
        SliverPersistentHeader(),
        SliverToBoxAdapter(),
        SliverFillRemaining(
        child: PaginateFirestore()
        )
    ]
)`

In this layout I am facing scrolling issues since slivers and paginate both have scrolling capability. Once I scroll and PaginateFirebase list occupies entire screen, it never never gets small on scrollback. Do you have any idea how can I stop this behavior?

**Comment by OutdatedGuy** [comment]
@Omi231 can you file a new issue with a minimal sample code
