### ISSUE TITLE
A ScrollController was used after being disposed[BUG] 

### ISSUE THREAD

**Issue by imugaibel** [OutdatedGuy/firebase_pagination#24]
## Describe the bug
I get this bug when I try to manually dispose scroll controller.

**Package version:**
3.0.0
**Platform:**
android 
IOS

**Comment by OutdatedGuy** [comment]
@imugaibel, why are you disposing the controller manually? Can you give more context?

**Comment by OutdatedGuy** [comment]
Closing as stale
