### ISSUE TITLE
[BUG] "Nothing found here..." is shown while there is data in the list

### ISSUE THREAD

**Issue by iAbdulaziz93** [OutdatedGuy/firebase_pagination#25]
## Describe the bug
Hi, I have two lists on the Firebase Real-time database, if I put `isLive: true` in the first list (which has the bug), the list keeps updating with showing the actual data in the list in the Firebase database and **"Nothing found here..."** at the same time (As shown in the video below). On the other hand, when I put `isLive: false`, the list shows **"Nothing found here..."** only without loading the data from the database. The second list (after the `Divider` in the below code) is loading without any issue while the code is almost the same compared to the first list's code and the data is coming from the same database but a different child!

**Package version: 3.0.0**
**Platform: Android**

### Expected behavior
1. `isLive: true` updates the UI when there is a new or edited value without continuous updates (non-sopping updates).
2. Data in the database/list should be displayed as normal.

### Actual behavior
1. UI keeps updating when `isLive: true` without stopping.
2. No data is shown in the list.

#### Screenshots/Code Snippets
**`coupons_categories_list` or `couponsCategoriesListDatabaseReference` is the list that has the above issue.**

```
SizedBox(
                        width: Get.width,
                        height: Get.height / 4.5,
                        child: RealtimeDBPagination(
                          query:
                              controller.couponsCategoriesListDatabaseReference,
                          itemBuilder: (buildContext, dataSnapshot, index) =>
                              CouponsCategoriesListWidget(
                            couponsController: controller,
                            selectedCouponCategories:
                                CouponsCategoriesListModel.fromJson(dataSnapshot
                                    .value as Map<dynamic, dynamic>),
                          ),
                          orderBy: 'type',
                          separatorBuilder: (buildContext, index) =>
                              const SizedBox(width: 10),
                          isLive: true,
                          //onEmpty: const CustomEmptyWidget(),
                          bottomLoader: customEasyLoading(),
                          initialLoader: customEasyLoading(),
                          scrollDirection: Axis.horizontal,
                        ),
                      ),
                      const Divider(color: AppColors.primaryColor),
                      SizedBox(
                        width: Get.width,
                        height: Get.height / 2,
                        child: RealtimeDBPagination(
                          query: controller.couponsListDatabaseReference,
                          itemBuilder: (buildContext, dataSnapshot, index) =>
                              CouponsListWidget(
                            couponsController: controller,
                            selectedCoupon: CouponsListModel.fromJson(
                                dataSnapshot.value as Map<dynamic, dynamic>),
                          ),
                          orderBy: 'name',
                          separatorBuilder: (buildContext, index) =>
                              const SizedBox(height: 10),
                          isLive: true,
                          onEmpty: const CustomEmptyWidget(),
                          bottomLoader: customEasyLoading(),
                          initialLoader: customEasyLoading(),
                        ),
                      ),
```

```
class CouponsController extends GetxController {
  FirebaseDatabase database = FirebaseDatabase.instance;
  late DatabaseReference couponsCategoriesListDatabaseReference;
  late DatabaseReference couponsListDatabaseReference;

  @override
  void onInit() {
    super.onInit();

    couponsCategoriesListDatabaseReference =
        database.ref('coupons_categories_list');
    couponsListDatabaseReference = database.ref('coupons_list');
  }
}
```

```
class CouponsCategoriesListModel {
  String? imageName;
  String? type;

  CouponsCategoriesListModel({
    this.imageName,
    this.type,
  });

  CouponsCategoriesListModel.fromJson(Map<dynamic, dynamic> json) {
    imageName = json['image_name'];
    type = json['type'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['image_name'] = imageName;
    data['type'] = type;
    return data;
  }
}
```

**Video of the issue:** [Video of the issue](https://files.fm/f/x9kacqrxd)

**Screenshot of the issue:** [Screenshot of the issue](https://files.fm/f/xtteywy9g)

**Screenshot of the real-time database:** [Screenshot of the real-time database](https://files.fm/f/c4xsfd6n2)

**Comment by OutdatedGuy** [comment]
Yo @iAbdulaziz93, a question just to confirm the problem.

So the list with bug is showing data properly when the `isLive` property is set to `true` and not working as intended when the value is set to `false`.

Also the data is continuously getting updated when `isLive` is `true`. Am I right?

**Comment by iAbdulaziz93** [comment]
Hi @OutdatedGuy,

Sorry for the late reply, I just edited the bug description above to make it more clear.

> Also the data is continuously getting updated when isLive is true. Am I right?

Yes, you're right.

**Comment by iAbdulaziz93** [comment]
Hi @OutdatedGuy, any update on this?

**Comment by OutdatedGuy** [comment]
@iAbdulaziz93, can you try changing the scroll direction of the bugged list to `vertical` and see if the issue persists.

Also please check if the realtime db rules are allowing data fetching for both `nodes`.

**Comment by iAbdulaziz93** [comment]
@OutdatedGuy, I tried changing the scroll direction to `vertical` and also the real-time database rules are allowing read and write as shown below. The issue still exists.

`{
  "rules": {
    ".read": "now < 1692046800000",  // 2023-8-15
    ".write": "now < 1692046800000",  // 2023-8-15
  }
}`

**Comment by OutdatedGuy** [comment]
@iAbdulaziz93 I see. Unfortunately, at this moment I am not actively maintaining this particular package.

Can you try using the [official firebase pagination package for realtime database](https://pub.dev/packages/firebase_ui_database).

I'll keep this issue open and solve it in the future when I get some free time.

**Comment by iAbdulaziz93** [comment]
Thanks, @OutdatedGuy!

I just tested the official package and it's working fine.
