### ISSUE TITLE
Not Seeing Bottom Loader

### ISSUE THREAD

**Issue by developer-farhan** [OutdatedGuy/firebase_pagination#26]
## Describe the bug
i have been using this plugin for sometime and I haven't seen the loader at all and im starting to think instead of pagination all documents are being called at once. I maybe wrong but please guide me on this 

firebase_pagination: ^3.0.0
Flutter/IOS

### Expected behavior
To show loader at the limit provided I dont think the limit is being respected

### Actual behavior
Straight up shows all the documents as if im using stream builder with no limits

#### Screenshots/Code Snippets

`FirebaseFirestore.instance
              .collection('x')
              .where('y', isEqualTo: z)
              .orderBy('a', descending: true)
              .limit(5)`

`FirestorePagination(
        limit: 5,
        isLive: true, // Defaults to false.
        viewType: ViewType.list,
        query: widget.firestoreQuery,
        bottomLoader: const Center(
          child: CircularProgressIndicator(
            strokeWidth: 3,
            color: Colors.blue,
          ),
        ),
        
      
      onEmpty:
          const Center(child: Card(child: Text('No data available - Empty'))),
      itemBuilder: (context, documentSnapshot, index) {
        final data = documentSnapshot.data() as Map<String, dynamic>?;
        if (data == null) {
          return const Center(child: Text('No data available'));
        }
        final document = data;
      

        return Widget();
      },
      separatorBuilder: (context, index) {
        return const Divider(
          height: 5,
          thickness: 1,
        );
      },
    );`

https://github.com/OutdatedGuy/firebase_pagination/assets/82877513/34fd5212-4107-4a2c-a9bc-4cb9df6a2a43

Also it may seem like im dragging while its loading but its not the list was already preloaded by many many docs

**Comment by OutdatedGuy** [comment]
Yo @officialFlutterDeveloper

I understand your issue. Unfortunately, at this moment I am not actively maintaining this particular package.

Can you try using the [official firebase pagination package for firestore](https://pub.dev/packages/firebase_ui_firestore).

I'll keep this issue open and solve it in the future when I get some free time.
