### ISSUE TITLE
isLive not working if i use two Order by 

### ISSUE THREAD

**Issue by saedfarashat** [OutdatedGuy/firebase_pagination#27]
hello everyone 
as i mention in the title .. the isLive not working if we use two order by .. thats mean if i use two OrderBy and i got i new data i need to rebuild my page to get the new data .. so Please fix this issue 
cause this Package is Amazing and making my day every time 
Thanks

**Comment by OutdatedGuy** [comment]
Yo @saedfarashat

Unfortunately, at this moment I am not actively maintaining this particular package.

Can you try using the [official firebase pagination package for firestore](https://pub.dev/packages/firebase_ui_firestore).

I'll keep this issue open and solve it in the future when I get some free time.

**Comment by OutdatedGuy** [comment]
> hello everyone as i mention in the title .. the isLive not working if we use two order by .. thats mean if i use two OrderBy and i got i new data i need to rebuild my page to get the new data .. so Please fix this issue cause this Package is Amazing and making my day every time Thanks

Yo @saedfarashat, if you are using two `orderBy` then you need a index in **firestore** or **realtime db**. Can you verify that you have created the necessary index by running the same type of query [here](https://console.firebase.google.com/project/outdated-projects/firestore/data?view=query-view)?
