### ISSUE TITLE
_streamSub triggers twice after initial load, setting isEnded to true prematurely

### ISSUE THREAD

**Issue by Mitchel0058** [OutdatedGuy/firebase_pagination#28]
## Describe the bug
_I read that you aren't maintaining this atm on other issues, but I thought it would at least be useful to know about this error in case you decided to do so at some point._
When a new set of data is loaded _streamSub gets fired twice, with the initial one having not having the new snapshots yet, causing the length to be the old amount while the docs limit is already updated in loadDocuments. loadDocuments only fires once as it should. The initial two load documents are correct in it getting the documents and applying the live listeners. 
This can be seen in the image provided below.

**Package version:** 3.0.0
**Platform:** FlutterFlow web

## To Reproduce
The widget I made: 
```
// Automatic FlutterFlow imports
import '/backend/backend.dart';
import '/backend/schema/structs/index.dart';
import '/flutter_flow/flutter_flow_theme.dart';
import '/flutter_flow/flutter_flow_util.dart';
import '/custom_code/widgets/index.dart'; // Imports other custom widgets
import '/custom_code/actions/index.dart'; // Imports custom actions
import '/flutter_flow/custom_functions.dart'; // Imports custom functions
import 'package:flutter/material.dart';
// Begin custom widget code
// DO NOT REMOVE OR MODIFY THE CODE ABOVE!

import 'dart:async';
import 'package:flutter/scheduler.dart';
import 'package:firebase_pagination/firebase_pagination.dart';

class Chat extends StatefulWidget {
  const Chat({
    Key? key,
    this.width,
    this.height,
    required this.chatMessagesRef,
    required this.paginationAmount,
  }) : super(key: key);

  final double? width;
  final double? height;
  final DocumentReference chatMessagesRef;
  final int paginationAmount;

  @override
  _ChatState createState() => _ChatState();
}

class _ChatState extends State<Chat> {
  late int paginationAmount;

  @override
  void initState() {
    super.initState();
    paginationAmount = widget.paginationAmount;
  }

  @override
  Widget build(BuildContext context) {
    return FirestorePagination(
      limit: paginationAmount,
      isLive: true,
      viewType: ViewType.list,
      reverse: true,
      query: widget.chatMessagesRef
          .collection('chatMessage')
          .orderBy('uploadTime', descending: true),
      itemBuilder: (context, documentSnapshot, index) {
        final data = documentSnapshot.data() as Map<String, dynamic>?;
        if (data == null) return Container();
        String? msg = data['message'];
        Timestamp timestamp = data['uploadTime'];
        DateTime dateTime = timestamp.toDate();
        String formattedDateTime =
            "${dateTime.hour.toString().padLeft(2, '0')}:${dateTime.minute.toString().padLeft(2, '0')} ${dateTime.day.toString().padLeft(2, '0')}-${dateTime.month.toString().padLeft(2, '0')}-${dateTime.year}";

        return ListTile(
          title: Text(
            (msg ?? 'no message') + '\n' + formattedDateTime,
          ),
        );
      },
      separatorBuilder: (context, index) {
        return const Divider(
          height: 5,
          thickness: 1,
        );
      },
    );
  }
}
```
Using this widget will not load more data after the first pagination. For some reason going back from the page and back into it allows it to load it correctly one extra time, so it does the first pagination correctly and then breaks, stacking with every back and forth so long as you load the last breaking pagination. It somehow gets the snapshot length correct on the first of the two fires from _streamSub in that case.

### Expected behavior
_streamSub does not trigger twice when fetching more data, correctly making isEnded not true due to the docs limit and snapshot limit being correct. 

### Actual behavior
_streamSub triggers twice after initial load, causing it to set isEnded to true prematurely.
For now I made a hotfix by copying the classes into my code and having it query the last document from firestore and comparing the id to set isEnded to true:

```
@override
  void initState() {
    super.initState();
    _initializeData();
    _loadDocuments();
    _controller.addListener(_scrollListener);
  }

  Future<void> _initializeData() async {
    lastDoc = await widget.query.limitToLast(1).get();
  }
```
```
      if (!_isEnded && !isDocRemoved) {
        _isEnded = (lastDoc!.docs.first.id == snapshot.docs.last.id);
      }
```

#### Screenshots/Code Snippets
![Schermafbeelding 2023-11-17 100815](https://github.com/OutdatedGuy/firebase_pagination/assets/90153171/884b484b-af0f-4888-a005-e54c2d3167b7)
The initial two load documents are the initial load and setting live listeners, after which it breaks.

#### Additional context
I don't know if this is a fault in how flutterflow is set up code wise or something else, but in run mode, which should be no different from an android emulator, this issue persists.

**Comment by OutdatedGuy** [comment]
Yo @Mitchel0058 

Ok, so the isEnded is falsely getting set to true if the documents length is not updated (it fires first time without updated data and second time with updated data).

So the fix might be to set isEnded every time, the data is received and if not equal (the second trigger) it'll set the value to `false`.

---

Please tell if the above explanation and solution is inferred correctly.

---

Also please elaborate on the issue like I'm **10** without any technical term so that I may get to understand the problem more clearly.

**Comment by Mitchel0058** [comment]
You said it correctly and that solution indeed worked! I'm suprised I overlooked such a simple solution.

To elaborate it simply, this part:
```
_streamSub = docsQuery.snapshots().listen((QuerySnapshot snapshot) async {
     ...
}
```
Gets activated twice (after the initial ones) and I do not know why. The first time it does so wrong, not having the information it should have, and the second time it does it correctly. 
The function above this, loadDocuments, correctly only gets activated once and I could not find where the second activation 
of _streamSub comes from. 

If you have any other questions for this or want elaboration on something I'd be glad to anwser.
