### ISSUE TITLE
I have some error first load firebase database

### ISSUE THREAD

**Issue by SunryTeang** [OutdatedGuy/firebase_pagination#3]
![Uploading Screen Shot 2022-08-18 at 3.37.25 PM.png…]()

**Comment by OutdatedGuy** [comment]
Yo @SunryTeang, looks like the image you intended to upload was interrupted. Can you upload it again.

**Comment by OutdatedGuy** [comment]
Closing this issue as no response was received.

If the problem still persists, leave comment and I'll reopen this issue.
