### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by quibenefacit** [OutdatedGuy/firebase_pagination#32]
## Describe the bug
When using RealtimeDBPagination, the limit value is being ignored. In the code below, all entries are being loaded from the database, not only 2, as requested by limit=2 .

**Package version:**
3.0.1

**Platform:**
Android and iOS

## To Reproduce
Here's the code:
```
@override
  Widget build(BuildContext context) {
    return RealtimeDBPagination(
            limit: 2, 
            isLive: true,
            reverse: true,
            orderBy: KEY_ID,
            shrinkWrap: true,
            query: FirebaseDatabase.instance.ref(TAB_MAIN).orderByKey(),
            itemBuilder: (context, snapshot, index) {
              final item = snapshot.value as Map<dynamic, dynamic>;
              return StreamBuilder(
                  stream: FirebaseDatabase.instance
                      .ref('$TAB_ENTRIES/${item[KEY_ENTITYID]}')
                      .onValue,
                  builder: (context, itemSnapshot) {
                    if (ConnectionState.waiting ==
                        itemSnapshot.connectionState) {
                      return const SizedBox.shrink();
                    } else if (itemSnapshot.hasError) {
                      return const ListTile(
                        title: Text('Error loading data'),
                      );
                    } else {         
                        WidgetsBinding.instance.addPostFrameCallback((_) {
                        // Code to be executed after the child widget has been built
                        print('index = $index');
                      });             
                        return ListTile(
                          title: Text('${item[KEY_ENTITYID]}'),
                          subtitle: const SizedBox(
                            height: 800,
                         ),
                        );                      
                    }
                  });
            });
  }
```

### Expected behavior
I expect only as many entries to be loaded and shown as there are specified by the limit value.

### Actual behavior
A clear and concise description of what is actually happening.

**Comment by OutdatedGuy** [comment]
Yo @quibenefacit, if `limit = 2` doesn't fill the scrolling area of the scrollable widget it's used in, it'll fetch new values till the Widget becomes scrollable.

This is an expected result if the above is true in your situation.

**Comment by quibenefacit** [comment]
No, I've made the items artificially tall (almost as high as the screen) just to test. 
But it still didn't respect limit=2. 
Try it yourself, you'll see.

**Comment by OutdatedGuy** [comment]
@quibenefacit how are you counting that all entries are loaded. Can you provide a video of the issue.

**Comment by quibenefacit** [comment]
I am counting by printing the value of index when the widget in itemBuilder finishes loading. 
I have updated the code above to show that. 
The output I get is attached: all 4 items in the database are loaded, even though I've only asked for 2. 
This output is produced BEFORE I do any scrolling. I should be only getting indexes 0 and 1, but I am also getting 2 and 3:
![Untitled3](https://github.com/OutdatedGuy/firebase_pagination/assets/66190809/17704626-fe46-4032-a636-3aaa20caed1a)

Also a video: 

<video src='https://github.com/OutdatedGuy/firebase_pagination/assets/66190809/11ddf65e-9df7-4d84-888e-4717035df871' width=180/>

**Comment by OutdatedGuy** [comment]
@quibenefacit, I understand your issue. Unfortunately, at this moment I am not actively maintaining this particular package.

Can you try using the [official firebase pagination package for realtime database](https://pub.dev/packages/firebase_ui_database).

I'll keep this issue open and solve it in the future when I get some free time.
