### ISSUE TITLE
with single index in itembuilder it loop through 4 times 

### ISSUE THREAD

**Issue by Jassirlink** [OutdatedGuy/firebase_pagination#35]
here i am using a chat application i have added this package for pagination , and also my chat list contain headerwidget that display the message send date , this widget works according to the itembuilder but when value of index is 0 itembuilder runs 4 times , this effect my headerwidget , please fix this bug

**Comment by OutdatedGuy** [comment]
Yo @Jassirlink, can you clarify more on what's the issue. Provide some [minimal reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) and also a screen recording with the issue.
