### ISSUE TITLE
Failed assertion: line 129 pos 7: 'value is String || value is bool || value is num || value == null'

### ISSUE THREAD

**Issue by p4-k4** [OutdatedGuy/firebase_pagination#4]
Using the following in a Column, couldn't see anything obvious as to what the problem might be. Any ideas?

Thanks

```dart
          RealtimeDBPagination(
            shrinkWrap: true,
            query: FirebaseDatabase.instance.ref().child('messages'),
            itemBuilder: (context, dataSnapshot, index) {
              final data = dataSnapshot.value as Map<String, dynamic>;
              return Text(data.toString());
            },
          ),
```

```bash
[VERBOSE-2:ui_dart_state.cc(198)] Unhandled Exception: 'package:firebase_database_platform_interface/src/query_modifiers.dart': Failed assertion: line 129 pos 7: 'value is String || value is bool || value is num || value == null': value must be a String, Boolean, Number or null.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      QueryModifiers._assertCursorValue (package:firebase_database_platform_interface/src/query_modifiers.dart:129:7)
#3      QueryModifiers.start (package:firebase_database_platform_interface/src/query_modifiers.dart:52:5)
#4      Query.startAt (package:firebase_database/src/query.dart:81:18)
#5      _RealtimeDBPaginationState._loadData (package:firebase_pagination/src/realtime_db_pagination.dart:193:29)
#6      _RealtimeDBPaginationState._loadData.<anonymous closure> (package:firebase_pagination/src/realtime_db_pagination.dart:217:17)
<asynchronous suspension>
```

**Comment by OutdatedGuy** [comment]
Yo @p4-k4, thanks for filling this issue. This is definitely a bug in the package itself. I'll fix it ASAP.

**Comment by p4-k4** [comment]
@OutdatedGuy all good. Was gonna have a crack at it but decided to roll my own from scratch. Nice package though :)

**Comment by OutdatedGuy** [comment]
Published fix to [pub](https://pub.dev)

**Comment by p4-k4** [comment]
> Published fix to [pub](https://pub.dev)

Cheers!

**Comment by p4-k4** [comment]
@OutdatedGuy seeing the following with the "fix"...

After checking the commit, I'm wondering, did you stage the actual fix? There's a version bump and stuff but can't see anything "fix" like. https://github.com/OutdatedGuy/firebase_pagination/commit/ce525824b4fb3ca3da9407b6cef13e4ea6f03211

```dart
          RealtimeDBPagination(
            shrinkWrap: true,
            isLive: true,
            query: database.ref().child('messages'),
            itemBuilder: (context, dataSnapshot, index) {
              return Text(dataSnapshot.value.toString());
            },
          ),
```

<img width="247" alt="Screen Shot 2022-08-31 at 7 21 41 PM" src="https://user-images.githubusercontent.com/61640764/187617878-c9183408-dbec-4eac-856d-95b60e291a83.png">

```shell
[VERBOSE-2:ui_dart_state.cc(198)] Unhandled Exception: 'package:firebase_database_platform_interface/src/query_modifiers.dart': Failed assertion: line 129 pos 7: 'value is String || value is bool || value is num || value == null': value must be a String, Boolean, Number or null.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      QueryModifiers._assertCursorValue (package:firebase_database_platform_interface/src/query_modifiers.dart:129:7)
#3      QueryModifiers.end (package:firebase_database_platform_interface/src/query_modifiers.dart:62:5)
#4      Query.endBefore (package:firebase_database/src/query.dart:124:18)
#5      _RealtimeDBPaginationState._setLiveListener (package:firebase_pagination/src/realtime_db_pagination.dart:237:39)
#6      _RealtimeDBPaginationState._loadData.<anonymous closure> (package:firebase_pagination/src/realtime_db_pagination.dart:221:28)
<asynchronous suspension>
```

**Comment by OutdatedGuy** [comment]
> After checking the commit, I'm wondering, did you stage the actual fix?

You looked at the wrong commit. The fix is [here](https://github.com/OutdatedGuy/firebase_pagination/pull/6).

Can you try making `message1` & `message2` into maps instead and see the result.

**Comment by p4-k4** [comment]
@OutdatedGuy you mean stringified maps? If so, same error as above.
<img width="247" alt="Screen Shot 2022-08-31 at 8 07 56 PM" src="https://user-images.githubusercontent.com/61640764/187626861-f350ed23-26e4-445f-920e-78a1f9dd6347.png">

**Comment by OutdatedGuy** [comment]
No, not like that. I meant to say, make the message1 and so as parent nodes instead.

Like:
```
¦
¦ -- messages
    ¦
    ¦ -- message1
        ¦
        ¦ -- text : "msg1"
    ¦
    ¦ -- message2
        ¦
        ¦ -- text : "msg2"
```

**Comment by p4-k4** [comment]
@OutdatedGuy Structuring that way will yield same results. Getting same error as above.

<img width="226" alt="Screen Shot 2022-08-31 at 8 54 02 PM" src="https://user-images.githubusercontent.com/61640764/187639452-03d34f5a-9e8e-4b67-b91a-73c5c6484e06.png">

```dart
RealtimeDBPagination(
            shrinkWrap: true,
            isLive: true,
            query: firebase_database.FirebaseDatabase.instance
                .ref()
                .child('messages'),
            itemBuilder: (context, dataSnapshot, index) {
              final data = dataSnapshot.value;
              return Text(data.toString());
            },
          )
```

`[VERBOSE-2:ui_dart_state.cc(198)] Unhandled Exception: 'package:firebase_database_platform_interface/src/query_modifiers.dart': Failed assertion: line 129 pos 7: 'value is String || value is bool || value is num || value == null': value must be a String, Boolean, Number or null.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      QueryModifiers._assertCursorValue (package:firebase_database_platform_interface/src/query_modifiers.dart:129:7)
#3      QueryModifiers.end (package:firebase_database_platform_interface/src/query_modifiers.dart:62:5)
#4      Query.endBefore (package:firebase_database/src/query.dart:124:18)
#5      _RealtimeDBPaginationState._setLiveListener (package:firebase_pagination/src/realtime_db_pagination.dart:237:39)
#6      _RealtimeDBPaginationState._loadData.<anonymous closure> (package:firebase_pagination/src/realtime_db_pagination.dart:221:28)
<asynchronous suspension>
`

**Comment by OutdatedGuy** [comment]
> package:firebase_pagination/src/realtime_db_pagination.dart:221:28

We are now getting error on different part of code. Thanks for reporting. I'll try to fix it.

**Comment by OutdatedGuy** [comment]
Can you check if the issue is resolved with the latest release.

**Comment by p4-k4** [comment]
@OutdatedGuy seems to be fine now thanks!
