### ISSUE TITLE
Possible to add Paging support?[Feature Request] 

### ISSUE THREAD

**Issue by tiltmaster** [OutdatedGuy/firebase_pagination#43]
Pretty much the title says it, There is list, grid and wrap, but is there a paging support to this one? or if possible to add paging support?

Much appreciated.

**Comment by OutdatedGuy** [comment]
Hi, I don't know what _paging_ is? Is it a scrolling type? If yes, can you provide some videos, gifs, and code references?

If feasible, I'll try to implement it.

As always, PRs are welcomed.

**Comment by godwin-mathias** [comment]
![kZNXj5](https://github.com/OutdatedGuy/firebase_pagination/assets/139175834/aa4477e3-fd03-4e88-a3e0-ed7dba97d672)

I think this is what OP meant by pagination. What we have currently in the package is an infinite scrollable list. Just a guess  though 🤷‍♂️

**Comment by tiltmaster** [comment]
> Hi, I don't know what _paging_ is? Is it a scrolling type? If yes, can you provide some videos, gifs, and code references?
> 
> If feasible, I'll try to implement it.
> 
> As always, PRs are welcomed.

Hi, really sorry for the late reply i somehow never got the notification, what I mean is that if its possible that it supports Pageview, since it supports listview and gridview, Pageview is probably one of highest demands out there, specially if it also supports preloading pages like Preload_pageview package. But that package is not being maintained and this one is firebase specific. 

To sum it up i would very much like to see it have a Pageview type, with options to preload pages with a threshold for how many pages to preload either up the list or below, as well as have a Seperator in order to perhaps insert specific Pages like Ad pages which would also be part of preloaded pages.

I do believe this change would be big.

Much appreciated.

**Comment by tiltmaster** [comment]
Sorry closed it by mistake

**Comment by OutdatedGuy** [comment]
@tiltmaster ohk, so a `PageView` widget using firebase pagination. Am I correct.

I'm currently busy with other stuffs, so will implement this feature when I get some free time.

As always, PRs are welcomed.

**Comment by tiltmaster** [comment]
> @tiltmaster ohk, so a `PageView` widget using firebase pagination. Am I correct.
> 
> I'm currently busy with other stuffs, so will implement this feature when I get some free time.
> 
> As always, PRs are welcomed.

Yes, along side preloading pages would be extremely huge, much appreciated.
