### ISSUE TITLE
Tracking the Number of Loaded Documents in itemBuilder [Feature Request] 

### ISSUE THREAD

**Issue by AignerMatthias** [OutdatedGuy/firebase_pagination#45]
**Is your feature request related to a problem? Please describe.**
I am currently using the FirestorePagination plugin for a messaging app and encountered a scenario where I need to determine whether the current document being rendered is the last one in the list of loaded documents. This is particularly important for displaying certain UI elements differently for the last item and managing state transitions.

**Describe the solution you'd like**
Can you extend the itemBuilder with the parameter loadedDocumentCount.
So I can check if it's the last document which is loaded.
itemBuilder: (context, documentSnapshot, index, int loadedDocumentCount)

**Comment by OutdatedGuy** [comment]
I can see how this is useful, but adding an extra parameter to `itemBuilder` would result in a breaking change update.

What I can do it, add an extra `paginationController` parameter to the `FirestorePagination` class that can access various methods and data from state of `FirestorePagination` class like `isEnded`, `isLoading`, `loadMoreDocs` etc.

However, I'm currently busy with other stuff, so will implement this when I get some free time.

As always, PRs are welcomed.
