### ISSUE TITLE
How can I apply filters on the data I fetch from firestore using the FirestorePagination widget? Before using this package I was using streamBuilder widget and I used to do the filters by editing the stream of the streamBuilder. 

### ISSUE THREAD

**Issue by bir8** [OutdatedGuy/firebase_pagination#46]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by OutdatedGuy** [comment]
@ahmed9hussin What kind of filters are you talking about? Can you explain this a bit more with examples and a sample code?

**Comment by bir8** [comment]
For example there is "status" field in each doc in the collection it's value could be "accepted", "rejected" or "onHold". This is an example of the stream of my streamBuilder : "FirebaseFirestore.instance
                          .collection('assignments')
                          .where('isDeleted', isEqualTo: false)
                          .where('status',
                              isEqualTo: assignmentController.assignmentStatus)
                          .orderBy('date', descending: true)
                          .snapshots(),". And I had a function that changes the value of the variable "assignmentStatus" in my controller then the filtered data will be fetched again in the streamBuilder widget. I tried to do the same in the FirestorePagination but It did not work. For example when I open the app the default value of "status" is "accepted" and the data get fetched successfully but when I change it to "onHold" the new filtered data would not be updated unless I scroll down, when I change it again to "rejected" for example it will not be updated again even If I scrolled down. If I did a mistake so correct me please and If you have a better idea I will be thankful. note the isLive property is "true".

Another example, now when I use the the FirestorePagination I will get all the docs in my collection and thats fine, but I want the user to be able to filter these data according to the date too (from & to) and I have a date field in my docs. How can I do this?

**Comment by ahmed9hussin** [comment]
> @ahmed9hussin What kind of filters are you talking about? Can you explain this a bit more with examples and a sample code?



> For example there is "status" field in each doc in the collection it's value could be "accepted", "rejected" or "onHold". This is an example of the stream of my streamBuilder : "FirebaseFirestore.instance .collection('assignments') .where('isDeleted', isEqualTo: false) .where('status', isEqualTo: assignmentController.assignmentStatus) .orderBy('date', descending: true) .snapshots(),". And I had a function that changes the value of the variable "assignmentStatus" in my controller then the filtered data will be fetched again in the streamBuilder widget. I tried to do the same in the FirestorePagination but It did not work. For example when I open the app the default value of "status" is "accepted" and the data get fetched successfully but when I change it to "onHold" the new filtered data would not be updated unless I scroll down, when I change it again to "rejected" for example it will not be updated again even If I scrolled down. If I did a mistake so correct me please and If you have a better idea I will be thankful. note the isLive property is "true".

**Comment by OutdatedGuy** [comment]
@ahmed9hussin What you can do is give the `key` parameter of `FirebasePagination` the value as `ValueKey(assignmentController.assignmentStatus)`. So whenever you change the value of `assignmentController.assignmentStatus` using `setState` it'll re-render the widget with your new firestore query.

Tell me if this works.

**Comment by nialljawad96** [comment]
@OutdatedGuy @ahmed9hussin This method works. Thanks!

**Comment by bir8** [comment]
> @ahmed9hussin What you can do is give the `key` parameter of `FirebasePagination` the value as `ValueKey(assignmentController.assignmentStatus)`. So whenever you change the value of `assignmentController.assignmentStatus` using `setState` it'll re-render the widget with your new firestore query.
> 
> Tell me if this works.

**Comment by bir8** [comment]
@OutdatedGuy Thanks a lot! it worked honestly you saved me I really appreciate your work. Just to understand when we assign a value to the key and that value changes the widget will be rendered again or what? can you explain for me more please I will appreciate it a lot. I closed it by mistake btw it's my first time using the issues in git :) but you already solved it so I think it's ok.

**Comment by OutdatedGuy** [comment]
When the value of the `key` parameter changes, the whole widget will be re-rendered (i.e. old firebase query and snapshot listeners will be cancelled and disposed, and all old resources will be released)
