### ISSUE TITLE
[Feature Request] get all snapshots from query

### ISSUE THREAD

**Issue by opxdelwin** [OutdatedGuy/firebase_pagination#47]
**Is your feature request related to a problem? Please describe.**
It's noted that the itemBuilder returns the `documentSnapshot` of the document in the given index, which is being iterated on. I'd like to get the list of snapshots from the firebase query, which would help me group the snapshots as per requirements. 

**Describe the solution you'd like**
I did see a variable `items` in the package codebase, which may be exposed, for specific use cases. It's common for such packages, even firestore official package to return all the snapshot documents. But we are exposing snapshot document at a specific index.

Maybe we can expose the variable in a new constructor and use it as an alternative to `itemBuilder`

**Describe alternatives you've considered**
If I'd want to implement this approach right now, I'll have to maintain a local list with all the snapshots, run query on the local list and build widgets using that.

**Additional context**
![image](https://github.com/OutdatedGuy/firebase_pagination/assets/84124091/7182db10-dd9c-4758-a770-ad09ea090ddd)

the callback function returning item at specific index, I'd like to get the entire `items` list exposed.
![image](https://github.com/OutdatedGuy/firebase_pagination/assets/84124091/d8a30837-a1ca-452d-af1b-9768626f98bb)

**Comment by OutdatedGuy** [comment]
Hi @opxdelwin, this is a good idea, but right now I'm busy so I cannot implement this soon. If you are interested then you can work on this and submit a PR.

I was thinking of publishing a breaking change anyhow with fixes for other pending issues.

So you can directly update the `itemBuilder` to send the full list at the end of parameters.

**Comment by opxdelwin** [comment]
Yup, I had implemented it in my fork. I'm not sure about the examples, and breaking test cases, but sure this would be a nice starting point. Compare [here](https://github.com/OutdatedGuy/firebase_pagination/compare/main...opxdelwin:firebase_pagination:main)

**Comment by OutdatedGuy** [comment]
@opxdelwin can you open a PR? The changes looks good, so we can check how this performs in test cases and all.

**Comment by opxdelwin** [comment]
Yup, done!

**Comment by OutdatedGuy** [comment]
Closing as completed in #48
