### ISSUE TITLE
[Feature Request] Access the docs variable to be able to reference previous and next items in list 

### ISSUE THREAD

**Issue by MissingLinkDev** [OutdatedGuy/firebase_pagination#50]
**Is your feature request related to a problem? Please describe.**
Working on a chat app and want to adjust how the message bubbles are displayed based on whether they are part of a group of messages or not.  Also would help determine when to show date separators inbetween messages for easier viewing.

**Describe the solution you'd like**
Already have access to the index in the item builder, would be great to have access to the _docs as well

**Describe alternatives you've considered**
Maybe an alternate version that returns a listbuilder instead of going all the way to item builder.  This would be nice to create custom lists easier

**Comment by OutdatedGuy** [comment]
There is already a PR in review for this issue. #48

**Comment by MissingLinkDev** [comment]
Oh nice, any idea when its gonna be merged?

**Comment by OutdatedGuy** [comment]
I'm currently very busy to merge and publish a new version. But if you have urgency, you can directly use that branch from the PR.

Like:

```yaml
dependencies:
  firebase_pagination:
    git:
      url: https://github.com/opxdelwin/firebase_pagination
      ref: main

**Comment by MissingLinkDev** [comment]
Awesome that works, will have to switch back to main build if you merge, but thats easy enough.  Thanks for the great plugin, saved me a lot of hassle of figuring it out myself
