### ISSUE TITLE
[Feature Request] Remove dependancy on firebase_database ^10.0.0 / Add support to work with firebase_database ^11.0.0

### ISSUE THREAD

**Issue by doinakis** [OutdatedGuy/firebase_pagination#52]
Hello!
Is there a reason that this package does not support firebase_database: ^11.0.0?

**Comment by OutdatedGuy** [comment]
> Is there a reason that this package does not support firebase_database: ^11.0.0?

Yes, because it was published only 2 days ago.

**Comment by doinakis** [comment]
> > Is there a reason that this package does not support firebase_database: ^11.0.0?
> 
> Yes, because it was published only 2 days ago.

Sorry about that I did not notice that! Thank you so much for the reply!!

**Comment by OutdatedGuy** [comment]
Will update all firebase dependencies in an upcoming PR.
