### ISSUE TITLE
[Feature Request] Add windows platform support

### ISSUE THREAD

**Issue by venky9885** [OutdatedGuy/firebase_pagination#59]
flutter firebase added support for windows ,so please update and add support for windows platform

**Comment by venky9885** [comment]
Use this version

cloud_firestore: ^5.2.1

**Comment by OutdatedGuy** [comment]
The package already support that version using the caret versioning. You just have to use the `cloud_firestore: ^5.2.1` on your side, no need to update the package.

But I don't know if the app will compile or not as this package also uses [firebase_database](https://pub.dev/packages/firebase_database) which still doesn't support the `windows` platform.
