### ISSUE TITLE
[Feature Request] OrderByChild with equalTo in Firebase RTDB

### ISSUE THREAD

**Issue by CodeWithBishal** [OutdatedGuy/firebase_pagination#61]
**Is your feature request related to a problem? Please describe.**
The current plugin works well by paginating data while fetching from a specific DB ref but there is no way of paginating data with search.

E.g. I have an ecommerce app that store all the order data from all the users in one collection.
Now in RTDB I will use ```FirebaseDatabase.instance.ref("Orders").orderByChild("UID").equalTo(user.uid)``` but that will fetch all the records from collection Orders containing UID = current user's UID but there is no way to pagination data. Earlier in the ```3.1.0``` version of the plugin I made it working by modifying the code according to my needs but I needed to update my firebase plugins and hence ```firebase_pagination``` also got updated to the latest version and now my code is broken and I though this will be helpful for everyone using the plugin if we get to a fix

**Comment by CodeWithBishal** [comment]
any thoughts @OutdatedGuy?

**Comment by CodeWithBishal** [comment]
Seems like the query ```.orderByChild("UID").equalTo(user.uid)``` already works when using the query parameter

**Comment by OutdatedGuy** [comment]
Sorry for late reply. But the `limit` parameter is set to 10 by default so the entire collection won't be fetched and only 10 docs are fetched each time when loading more data.
