### ISSUE TITLE
[Feature Request] Firebase does not support in-depth filtering. Please provide a solution for filtering data efficiently.

### ISSUE THREAD

**Issue by moinkhan780** [OutdatedGuy/firebase_pagination#63]
Example: Social Media Posts

I want to filter posts by IDs (reported post IDs). I have an array of IDs that I want to use to filter posts from a Firebase collection on the client side.

**Comment by OutdatedGuy** [comment]
@moinkhan780 can you verify if this PR meets your requirements? https://github.com/OutdatedGuy/firebase_pagination/pull/62

**Comment by moinkhan780** [comment]
> @moinkhan780 can you verify if this PR meets your requirements? #62

Yes, if it can match my case where I need to remove data from the list when the ID matches, or otherwise.
