### ISSUE TITLE
Please make the search and  filters data with firestore pagination 

### ISSUE THREAD

**Issue by Muhammad-Faisal-malana** [OutdatedGuy/firebase_pagination#66]

**Comment by OutdatedGuy** [comment]
Hi @Muhammad-Faisal-malana, currently I'm not actively maintaining this package. Can you try using the [official firestore pagination package](https://pub.dev/packages/firebase_ui_firestore)?

**Comment by OutdatedGuy** [comment]
Closing as completed in #62
